### ISSUE TITLE
[BUG] Groups Config Gets Erased Randomly

### ISSUE THREAD

**Issue by gotbletu** [Nukesor/pueue#116]
**Describe the bug**

I can't really reproduce it as it happens randomly but it happens a few times already. The program would be working perfect for a few mins/hours/days then i would get the error message below. I have not touch any config files. Only been using it from the commandline. I do have a few pueue groups. which i think is the cause of the issue since if i compare the config files in the beginning and when i get the error is totally different. The groups gets delete from the configs somehow.

`$ pueued -d && sleep 3 && pueue group --add fm && pueue group --add cl && pueue group --add dl && pueue group --add wb && pueue group --add vids && pueue group --add clips`

#### NOT WORKING
```
Error: mapping values are not allowed in this context at line 13 column 13 in .config/pueue.yml
```

$ cat ~/.config/pueue.yml
```
---
client:
  daemon_port: "6924"
  secret: ROJRqR1K9nptpKl!4F%1
  read_local_logs: true
daemon:
  pueue_directory: /home/heoyea-ant/.local/share/pueue
  port: "6924"
  secret: ROJRqR1K9nptpKl!4F%1
  default_parallel_tasks: 1
  pause_on_failure: false
  callback: ~
  groups: {}: {}
```

#### Temporary Fix
1. killall pueued
2. rm ~/.config/pueue.yml
3. pueued -d && sleep 3 && pueue group --add fm && pueue group --add cl && pueue group --add dl && pueue group --add wb && pueue group --add vids && pueue group --add clips

#### WORKING
$ cat ~/.config/pueue.yml
```
---
client:
  daemon_port: "6924"
  secret: "*Oimyf*M4YB#Jtg&Pj~l"
  read_local_logs: true
daemon:
  pueue_directory: /home/heoyea-ant/.local/share/pueue
  port: "6924"
  secret: "*Oimyf*M4YB#Jtg&Pj~l"
  default_parallel_tasks: 1
  pause_on_failure: false
  callback: ~
  groups:
    wb: 1
    dl: 1
    vids: 1
    fm: 1
    clips: 1
    cl: 1
```

**Additional context**
- Kernel: 5.8.12-arch1-1 x86_64 bits: 64 Desktop: Xfce 4.14.2 Distro: Antergos Linux
- Pueue client 0.7.2
