### ISSUE TITLE
[BUG] Unix sockets not used by default on unix systems

### ISSUE THREAD

**Issue by rkanati** [Nukesor/pueue#165]
The [changelog](https://github.com/Nukesor/pueue/blob/master/CHANGELOG.md#0100---29-12-2020) states that unix sockets will be used by default on unix systems as of 0.10. This does not appear to be the case.

**To Reproduce**
1. Clear out `~/.config/pueue` and `~/.local/share/pueue`
2. Start `pueued`
3. Note that `shared.use_unix_socket` is `false` in `pueue.yml`, and `pueue` attempts to make a TLS connection to the daemon.

**Expected behavior**
The generated configuration should specify `shared.use_unix_socket` as `true`.

**Additional context**
- Arch Linux
- `pueue 0.10.2` installed via `cargo`

**Comment by rkanati** [comment]
Follow-up: After some significant frustration, I installed `0.10.2` from Arch's AUR, and it doesn't exhibit this issue. I wondered if this was a build configuration issue, but the `PKGBUILD` (the script used to build `pueue` into an Arch package) seems innocent. Perhaps `cargo` is doing something wrong here?

I'm happy for this to be closed, but the inconsistency seems to warrant further investigation, even if it just results in a warning for users not to use `cargo install pueue`.

**Comment by Nukesor** [comment]
Did you have an old version of pueue installed prior to the upgrade to `0.10.2`?
I just did a quick test and new configuration files do have the correct configuration `use_unix_socket: true` set in `~/.config/pueue/pueue.yml`.

You could do a quick validation of this bug:

1. Stop the daemon
2. Copying `~/.config/pueue` to some other location
3. Start the daemon again
4. Check the config file, if the boolean is set correctly.

**Comment by Nukesor** [comment]
Unix sockets were introduced a few versions ago, but they weren't enabled by default.
This has changed with `0.10.2`, but this only works for new versions.

**Comment by Nukesor** [comment]
> Follow-up: After some significant frustration, I installed `0.10.2` from Arch's AUR, and it doesn't exhibit this issue. I wondered if this was a build configuration issue, but the `PKGBUILD` (the script used to build `pueue` into an Arch package) seems innocent. Perhaps `cargo` is doing something wrong here?
> 
> I'm happy for this to be closed, but the inconsistency seems to warrant further investigation, even if it just results in a warning for users not to use `cargo install pueue`.

This is rather weird.
A fresh installation should do nothing. The value is read from the configuration file, which is only created once at the first start of the `pueued` daemon. Uninstalling Pueue doesn't remove the user configuration file.

I'm using `cargo install` for local development and the AUR package for the rest of my machines, but I've never encountered this issue...

This is really weird.

**Comment by Nukesor** [comment]
Sorry if I didn't read your initial post thoroughly enough.
I've been coding for the past 10+ hours and my brain is slowly turning into mush :sweat_smile:

**Comment by Nukesor** [comment]
Ok. I tried to reproduce this issue.

Here's what I did:

1. I wiped any pueue install of my system and killed all running `pueued` instances.
2. Install via `cargo install`

```
[nuke:~/.config] % ls pueue
[nuke:~/.config] 130 % rm -r pueue
[nuke:~/.config] % pueued -V
Pueue daemon 0.10.2
[nuke:~/.config] % pueued
[nuke:~/.config] % cat pueue/pueue.yml
---
client:
  read_local_logs: true
  show_confirmation_questions: false
  show_expanded_aliases: false
  max_status_lines: ~
daemon:
  default_parallel_tasks: 1
  pause_group_on_failure: false
  pause_all_on_failure: false
  callback: ~
  groups: {}
shared:
  pueue_directory: /home/nuke/.local/share/pueue
  use_unix_socket: true
  unix_socket_path: /home/nuke/.local/share/pueue/pueue_nuke.socket
  host: localhost
  port: "6924"
  daemon_cert: /home/nuke/.local/share/pueue/certs/daemon.cert
  daemon_key: /home/nuke/.local/share/pueue/certs/daemon.key
  shared_secret_path: /home/nuke/.local/share/pueue/shared_secret%             
  ```
The same result can be seen when using either the `pueue` or the `pueue-bin` AUR package.

I kind of suspect, that there was some old `pueued` still running in the background, which overwrote the new configuration version.
