### ISSUE TITLE
[BUG] Stop modifying existing configuration file

### ISSUE THREAD

**Issue by dgengtek** [Nukesor/pueue#232]
**Describe the bug**
pueued is adding missing defaults to an existing configuration file `~/.config.pueue/pueue.yml`

**To Reproduce**
Restart pueued with a config file which has for example only this

```
client:
  status_time_format: "%H:%M:%S"
  status_datetime_format: "%Y-%m-%d\n%H:%M:%S"
```

on restart of pueued it adds defaults for the daemon and shared key and any missing configs in client

```
client:
  restart_in_place: false
  read_local_logs: true
  show_confirmation_questions: false
  show_expanded_aliases: false
  dark_mode: false
  max_status_lines: ~
  status_time_format: "%H:%M:%S"
  status_datetime_format: "%Y-%m-%d\n%H:%M:%S"
daemon:
  default_parallel_tasks: 1
   ...
shared:
  use_unix_socket: true
  host: 127.0.0.1
  port: "6924"
```

**Expected behavior**
I don't think this behavior is reasonable. No app should modify an existing configuration. It is fine that a default configuration is generated if none currently exists but if the file exists an app should not modify it but only read it to check if it is valid.

**Additional context**
Pueue client 1.0.1
