### ISSUE TITLE
Multi-user Question

### ISSUE THREAD

**Issue by EntilZha** [Nukesor/pueue#423]
I had a quick question about multi-user, in the design goals its stated as a non-goal, but wanted to see what that meant exactly. Namely, is it possible to use a single instance of pueue on one machine from multiple users, with the understanding that we will be queuing things using the same queue? E.G., would each command run under our user or the user that started `pueued`? Mostly looking to see what behavior to expect if we try using pueue from multiple users.

**Comment by Nukesor** [comment]
Pueue has been designed to be run by a single-user.
It's easy to run multiple pueued instances on the same system, especially in the Unix default mode with unix sockets. TCP sockets will need some manual port handling to avoid conflicts.

It's possible to run the daemon and have it expose a port/unix socket to multiple users, but commands would always be executed by the user that started the daemon.

-> Multi-user setups where each command is executed in the scope of the respective user isn't in the scope of this project and would need a significant refactoring. It would also require the daemon to run as `root`.

**Comment by Nukesor** [comment]
Also, if you plan to run such a setup and manage to do so, it would be great if you could add a small guide to the wiki :)

**Comment by Nukesor** [comment]
@EntilZha Does this answer your question :)?

**Comment by da-i** [comment]
I Tried to setup such a multi user queue on a VM. So I installed Pueue with cargo, made a service, and created a config with a socket in a readable location. In the end i got something that worked pretty well out of the box, but i need to tweak the permissions a bit.


The Service ended up looking like this, probably should have called it pueued, as that is what it actually is running.
```
$cat  /etc/systemd/system/pueue.service
[Unit]
Description=Pueue Queueing system

[Service]
User=root
Execstart=/home/user/.cargo/bin/pueued =c /etc/pueue/config.yml
Restart=always
```
afterwards i did a sudo systemctl daemon-reload and sudo service pueue restart

Next we needed to make the config, maybe we should have done that first?? Anyway this is what I ended up with. Its all the defaults but modified pueue_directory and unix_socket_path.

```
$cat /etc/pueue/config.yml
---
shared:
  pueue_directory: /etc/pueue
  use_unix_socket: true
  runtime_directory: null
  unix_socket_path: /etc/pueue/pueue.socket
  host: "localhost"
  port: "6924"
  daemon_cert: ~/.local/share/pueue/certs/daemon.cert
  daemon_key: ~/.local/share/pueue/certs/daemon.key
  shared_secret_path: ~/.local/share/pueue/shared_secret

client:
  restart_in_place: false
  read_local_logs: true
  show_confirmation_questions: false
  show_expanded_aliases: false
  dark_mode: false
  max_status_height: null
  status_time_format: "%H:%M:%S"
  status_datetime_format: "%Y-%m-%d\n%H:%M:%S"

daemon:
  default_parallel_tasks: 1
  pause_group_on_failure: false
  pause_all_on_failure: false
  callback: ""Task {{ id }}\nCommand: {{ command }}\nPath: {{ path }}\nFinished with status '{{ result }}'\""
  callback_log_lines: 10
  groups:
    default: 1
```

When i ran Pueue with sudo pueue -c /etc/pueue/config.yml, it works as intended.

But without sudo i got:
```
Error: Failed to initialize client.
Caused by:
0: Failed to initialize stream.
1: I/O error at path "/etc/pueue/pueue.socket" while connecting to daemon. Did you start it?
Permission denied (os error 13)
```

giving read permissions to all new files in /etc/pueue fixed the issue! So i can now add and view commands with both the root and the user user. 

Will see how i can improve things in the near future. Just wanted to put this here for people when they find this issue :).
