### ISSUE TITLE
Custom pueue aliases

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#62]
It would be pretty cool to allow users to use their custom shells with custom arguments.

This could be done via a new section in `pueue.yml`:
```
shell:
   command: 'bash'
   arguments:
      - '--rcfile'
      - '~/.config/pueue_alias_bashrc'
      - '-c'
```
